export const MessageType  = {
  TEXT_SELECTED: 'TEXT_SELECTED',
  CHAT_REQUEST: 'CHAT_REQUEST',
  CHAT_RESPONSE: 'CHAT_RESPONSE',
  ERROR: 'ERROR',
  UPDATE_USER_INFO: "UPDATE_USER_INFO",
  GET_SELECTED_TEXT_REQUEST: 'GET_SELECTED_TEXT_REQUEST',
  GET_SELECTED_TEXT_RESPONSE: 'GET_SELECTED_TEXT_RESPONSE',
  SELECTED_MODEL: "SELECTED_MODEL",
  OPEN_CHAT_TAB: 'OPEN_CHAT_TAB',
  USER_SETTINGS:{
    UPDATE_LANGUAGE: 'USER_SETTINGS.UPDATE_LANGUAGE',
    UPDATE_THEME: 'USER_SETTINGS.UPDATE_THEME'
  }
} as const;
